In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
print(dataset.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [7]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
df['target']=dataset.target

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                5.1               3.5                1.4               0.2  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
df['target'].unique()

array([0, 1, 2])

In [43]:
# convert in to 2 oputput
df_copy=df[df['target']!=2]

In [14]:
df_copy['target'].unique()

array([0, 1])

In [16]:
from sklearn.model_selection import train_test_split

In [28]:
X=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
classification=LogisticRegression(max_iter=200)

In [32]:
classification

LogisticRegression(max_iter=200)

In [33]:
classification.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [36]:
y_pred=classification.predict(X_test)

In [37]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

### calculate confussion matrics , Accuracy, classification Report

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [40]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [41]:
print(accuracy_score(y_test, y_pred))

1.0


In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# crass validation

In [44]:
from sklearn.model_selection import KFold

In [47]:
cv=KFold(n_splits=5, shuffle=True)

In [48]:
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [49]:
from sklearn.model_selection import cross_val_score

In [53]:
## these are my the score for the cross validation 
scores=cross_val_score(classification, X_train, y_train, scoring='accuracy', cv=cv)

In [54]:
np.mean(scores)

1.0

In [55]:
## lets see for mor compex data 

from  sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

X, y= make_classification(n_samples=1000, n_features=10, n_redundant=5, n_classes=2, random_state=1)

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [59]:
complex_class_model=LogisticRegression(max_iter=200)

In [60]:
complex_class_model.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [62]:
y_pred_complex=complex_class_model.predict(X_test)

In [64]:
print(confusion_matrix(y_test,y_pred_complex))

[[82 12]
 [10 96]]


In [65]:
print(accuracy_score(y_test,y_pred_complex))

0.89


In [66]:
print(classification_report(y_test,y_pred_complex))

              precision    recall  f1-score   support

           0       0.89      0.87      0.88        94
           1       0.89      0.91      0.90       106

    accuracy                           0.89       200
   macro avg       0.89      0.89      0.89       200
weighted avg       0.89      0.89      0.89       200



In [67]:
cv=KFold(n_splits=5, shuffle=True)
scores_1=cross_val_score(classification, X_train, y_train, scoring='accuracy', cv=cv)
np.mean(scores_1)

0.83375

In [68]:
scores_1

array([0.81875, 0.825  , 0.825  , 0.83125, 0.86875])