In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(float(range(0.4,10.4)))

TypeError: 'float' object cannot be interpreted as an integer

# 1.   $arange(start, stop, step,):$ Return evenly spaced values within a given interval.
* range function can not support the floating points. 
* in numpy arrange is a function that gives the floating point range also

In [5]:
np.arange(0.4, 10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [7]:
np.arange(0.4, 10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [8]:
list(np.arange(0.4, 10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

# 2. $np.linspace(start, stop, num)$

* Return evenly spaced numbers over a specified interval.
* Returns `num` evenly spaced samples, calculated over the 
interval [`start`, `stop`].

In [10]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
np.linspace(1,3,20)

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [12]:
np.linspace(1,20,20)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

# 3. $np.logspace(start, stop, num):$
* Return numbers spaced evenly on a log scale.

In [13]:
np.logspace(1,5,20)

array([1.00000000e+01, 1.62377674e+01, 2.63665090e+01, 4.28133240e+01,
       6.95192796e+01, 1.12883789e+02, 1.83298071e+02, 2.97635144e+02,
       4.83293024e+02, 7.84759970e+02, 1.27427499e+03, 2.06913808e+03,
       3.35981829e+03, 5.45559478e+03, 8.85866790e+03, 1.43844989e+04,
       2.33572147e+04, 3.79269019e+04, 6.15848211e+04, 1.00000000e+05])

In [14]:
np.logspace(1,5,20, base=2)

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

# 4 $np.zeros((shape)):$
* Return a new array of given shape and type, filled with zeros.

In [15]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
np.zeros((4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

# 5 $np.ones((shape )):$
* Return a new array of given shape and type, filled with ones.

In [23]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [26]:
np.ones((2,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [24]:
arr=np.ones((3,4))

In [25]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

# 6 $np.empty((shape)):$
* Return a new array of given shape and type, without initializing entries.

In [28]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

# 7 $ np.eye(Number of rows):$
* Return a 2-D array with ones on the diagonal and zeros elsewhere.
* it is an Identity matrix
* determinant of this matrix =1
* It is always a square matrix [no. of rows = no. of column]

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# can you convert the array to data points

In [34]:
arr2=np.eye(5)

In [32]:
import pandas as pd

In [35]:
pd.DataFrame(arr2)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

# 8 $ np.random.rand (size):$
* Random values in a given shape.

In [36]:
np.random.rand(2,3)

array([[0.94811551, 0.47562144, 0.71643535],
       [0.33247183, 0.06913959, 0.345811  ]])

# 9 $ np.random.randn (size):$
* Return a sample (or samples) from the "standard normal" distribution.
*  means mean=0 and SD=1

In [37]:
np.random.randn(2,3)

array([[-0.42418346,  0.52074201, -0.54793762],
       [ 2.22619109, -0.67134719,  1.99476473]])

# 10 $ np.random.randint(low, high, (size)):$
* Return random integers from `low` (inclusive) to `high` (exclusive).

In [41]:
np.random.randint(1,5,(3,4) )

array([[2, 2, 1, 1],
       [1, 2, 4, 4],
       [4, 4, 1, 1]])

In [42]:
arr3=np.random.randint(1,5,(3,4) )

In [43]:
arr3.size

12

In [44]:
arr3.shape

(3, 4)

# 11  array_name.reshape(shape, order='C):
* Returns an array containing the same data with a new shape.


In [45]:
arr3.size

12

* Note:-- now you have to reshape but in the multiple of its previous size

e.g  'arr3.shape=12'   then choose multiple of 12

(3,4), (4,3), (2,6),(6,2), (1,12),(12,1), (2,2,3),(4,-1),(6,-1)

In [46]:
arr3.reshape(2,6)

array([[3, 2, 2, 3, 3, 1],
       [2, 3, 3, 1, 4, 1]])

In [47]:
arr3.reshape(2,2,3)

array([[[3, 2, 2],
        [3, 3, 1]],

       [[2, 3, 3],
        [1, 4, 1]]])

In [48]:
arr3.reshape(4,-1)

array([[3, 2, 2],
       [3, 3, 1],
       [2, 3, 3],
       [1, 4, 1]])

In [49]:
arr3.reshape(6,-1)

array([[3, 2],
       [2, 3],
       [3, 1],
       [2, 3],
       [3, 1],
       [4, 1]])

In [50]:
arr3.reshape(2,2,3,1,1,1)

array([[[[[[3]]],


         [[[2]]],


         [[[2]]]],



        [[[[3]]],


         [[[3]]],


         [[[1]]]]],




       [[[[[2]]],


         [[[3]]],


         [[[3]]]],



        [[[[1]]],


         [[[4]]],


         [[[1]]]]]])

# 12  conditaion statment:  Filter out data

In [89]:
arr4=np.random.randint(1,10,(5,6))

In [90]:
arr4

array([[3, 5, 8, 7, 8, 1],
       [3, 4, 6, 9, 7, 9],
       [3, 3, 2, 4, 7, 5],
       [1, 2, 4, 3, 6, 7],
       [2, 1, 6, 5, 4, 3]])

In [91]:
arr4>8

array([[False, False, False, False, False, False],
       [False, False, False,  True, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [92]:
arr4[arr4>8]

array([9, 9])

In [93]:
arr4[0,[0,1]]

array([3, 5])

In [94]:
arr4[0][0:2]

array([3, 5])

In [95]:
arr4[2:4,[2,3]] # slicing and indexing

array([[2, 4],
       [4, 3]])

# 13 $ Math:$

In [99]:
arr4=np.random.randint(1,3,(3,3))
arr5=np.random.randint(1,3,(3,3))

In [100]:
arr4

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [101]:
arr5

array([[2, 1, 2],
       [2, 1, 1],
       [1, 2, 2]])

In [102]:
arr4+arr5  #addition index wise

array([[4, 2, 4],
       [4, 2, 3],
       [2, 4, 3]])

In [103]:
arr4-arr5 # substraction index wise

array([[ 0,  0,  0],
       [ 0,  0,  1],
       [ 0,  0, -1]])

In [104]:
arr4*arr5 #  multiplication index wise

array([[4, 1, 4],
       [4, 1, 2],
       [1, 4, 2]])

In [105]:
arr4/arr5 #division index wise

array([[1. , 1. , 1. ],
       [1. , 1. , 2. ],
       [1. , 1. , 0.5]])

## Matrix multiplication

In [106]:
arr4@arr5

array([[8, 7, 9],
       [8, 7, 9],
       [7, 5, 6]])

In [107]:
arr4/0

C:\Users\meshr\AppData\Local\Temp\ipykernel_9760\1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

# 14 $ Broadcasting$

In [120]:
arr6=np.zeros((3,4)) # (R, c)

In [121]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
arr6+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [123]:
arr6*5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
arr6/5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
arr6-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [126]:
a=np.array([1,2,3,4])

In [135]:
arr6+a # added column wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [131]:
b=np.array([[3,4,5]]) # cant roted 1D theirfor 2D[[]]

In [136]:
arr6+b.T # added Row wise (transpose 2D array)

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [137]:
arr7=arr6+b.T

In [138]:
np.square(arr7)

array([[ 9.,  9.,  9.,  9.],
       [16., 16., 16., 16.],
       [25., 25., 25., 25.]])

In [139]:
np.log10(arr7)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [140]:
np.exp(arr7)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [143]:
arr7

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [141]:
np.min(arr7)

3.0

In [142]:
np.max(arr7)

5.0