In [2]:
import numpy as np

# Numpy- Array manupulation

In [13]:
arr=np.random.randint(1,10,(4,4))

In [14]:
arr

array([[1, 8, 6, 3],
       [7, 8, 6, 3],
       [3, 6, 5, 7],
       [9, 8, 8, 7]])

In [15]:
arr.reshape(8,2)

array([[1, 8],
       [6, 3],
       [7, 8],
       [6, 3],
       [3, 6],
       [5, 7],
       [9, 8],
       [8, 7]])

In [17]:
arr.T

array([[1, 7, 3, 9],
       [8, 8, 6, 8],
       [6, 6, 5, 8],
       [3, 3, 7, 7]])

# 1. convert into 1d 

In [18]:
arr.flatten()

array([1, 8, 6, 3, 7, 8, 6, 3, 3, 6, 5, 7, 9, 8, 8, 7])

In [20]:
arr

array([[1, 8, 6, 3],
       [7, 8, 6, 3],
       [3, 6, 5, 7],
       [9, 8, 8, 7]])

# 2. np.expand_dims(Name_Of_array, axis):
* Expand the shape of an array.
* converted from 1 dimension(lesser) to another dimension(higher)

In [24]:
np.expand_dims(arr, axis=1) # across the column

array([[[1, 8, 6, 3]],

       [[7, 8, 6, 3]],

       [[3, 6, 5, 7]],

       [[9, 8, 8, 7]]])

In [29]:
np.expand_dims(arr, axis=0) # across the row & convverted to 2 Diamention to 3 diamention

array([[[1, 8, 6, 3],
        [7, 8, 6, 3],
        [3, 6, 5, 7],
        [9, 8, 8, 7]]])

# 3. np.squeeze(Name_Of_array, axis):
* converted from 1 dimension(higher) to another dimension (lesser)

In [33]:
data= np.array([[1],[2],[3]])

In [34]:
np.squeeze(data, axis=1)

array([1, 2, 3])

# 4. np.repeat(Name_of_array, repeats, axis)
* repeat elements of an array.

In [41]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [40]:
np.repeat(data,4, axis=1)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [42]:
np.repeat(data,4, axis=0)

array([[1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3]])

# 5. np.roll(name_array, shift)
* Roll array elements along a given axis.
* it roated the data set

In [46]:
data

array([[1],
       [2],
       [3]])

In [43]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [44]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [45]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

# 6. np.diag()
* Extract a diagonal or construct a diagonal array.

In [48]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [51]:
data1=[1,2,3,4,5,6,7,8,9,10]

In [52]:
np.array_split(data1, 2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [53]:
np.array_split(data1, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

# 7. Bianary operation

In [57]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [58]:
arr1

array([[5, 2, 9, 9],
       [9, 6, 5, 7],
       [7, 7, 8, 4]])

In [59]:
arr2

array([[9, 3, 3, 6],
       [4, 4, 7, 9],
       [7, 5, 6, 6]])

In [60]:
arr1 +arr2

array([[14,  5, 12, 15],
       [13, 10, 12, 16],
       [14, 12, 14, 10]])

In [62]:
arr1*arr2

array([[45,  6, 27, 54],
       [36, 24, 35, 63],
       [49, 35, 48, 24]])

In [63]:
arr1-arr2

array([[-4, -1,  6,  3],
       [ 5,  2, -2, -2],
       [ 0,  2,  2, -2]])

In [64]:
arr1/arr2

array([[0.55555556, 0.66666667, 3.        , 1.5       ],
       [2.25      , 1.5       , 0.71428571, 0.77777778],
       [1.        , 1.4       , 1.33333333, 0.66666667]])

In [65]:
arr1**arr2

array([[ 1953125,        8,      729,   531441],
       [    6561,     1296,    78125, 40353607],
       [  823543,    16807,   262144,     4096]])

In [66]:
~ arr1

array([[ -6,  -3, -10, -10],
       [-10,  -7,  -6,  -8],
       [ -8,  -8,  -9,  -5]])

In [67]:
arr1>arr2

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [False,  True,  True, False]])

In [68]:
arr1<arr2

array([[ True,  True, False, False],
       [False, False,  True,  True],
       [False, False, False,  True]])

# 8. String operation

In [70]:
arr3=np.array(['nutan', 'gargie'])

In [71]:
arr3

array(['nutan', 'gargie'], dtype='<U6')

In [72]:
np.char.upper(arr3)

array(['NUTAN', 'GARGIE'], dtype='<U6')

In [73]:
np.char.lower(arr3)

array(['nutan', 'gargie'], dtype='<U6')

In [75]:
np.char.title(arr3)

array(['Nutan', 'Gargie'], dtype='<U6')

# 9. Mathematical function

In [77]:
arr1

array([[5, 2, 9, 9],
       [9, 6, 5, 7],
       [7, 7, 8, 4]])

In [76]:
np.sin(arr1)

array([[-0.95892427,  0.90929743,  0.41211849,  0.41211849],
       [ 0.41211849, -0.2794155 , -0.95892427,  0.6569866 ],
       [ 0.6569866 ,  0.6569866 ,  0.98935825, -0.7568025 ]])

In [78]:
np.cos(arr1)

array([[ 0.28366219, -0.41614684, -0.91113026, -0.91113026],
       [-0.91113026,  0.96017029,  0.28366219,  0.75390225],
       [ 0.75390225,  0.75390225, -0.14550003, -0.65364362]])

In [79]:
np.tan(arr1)

array([[-3.38051501, -2.18503986, -0.45231566, -0.45231566],
       [-0.45231566, -0.29100619, -3.38051501,  0.87144798],
       [ 0.87144798,  0.87144798, -6.79971146,  1.15782128]])

In [81]:
np.log10(arr1)

array([[0.69897   , 0.30103   , 0.95424251, 0.95424251],
       [0.95424251, 0.77815125, 0.69897   , 0.84509804],
       [0.84509804, 0.84509804, 0.90308999, 0.60205999]])

In [82]:
np.log2(arr1)

array([[2.32192809, 1.        , 3.169925  , 3.169925  ],
       [3.169925  , 2.5849625 , 2.32192809, 2.80735492],
       [2.80735492, 2.80735492, 3.        , 2.        ]])

In [83]:
np.exp(arr2)

array([[8103.08392758,   20.08553692,   20.08553692,  403.42879349],
       [  54.59815003,   54.59815003, 1096.63315843, 8103.08392758],
       [1096.63315843,  148.4131591 ,  403.42879349,  403.42879349]])

In [85]:
np.power(arr1,2)

array([[25,  4, 81, 81],
       [81, 36, 25, 49],
       [49, 49, 64, 16]], dtype=int32)

In [86]:
np.min(arr1)

2

In [88]:
np.mean(arr1)

6.5

In [89]:
np.var(arr1)

4.416666666666667

In [90]:
np.std(arr1)

2.101586702153082

In [92]:
np.max(arr1)

9

# 10. Arithmatic operation

In [94]:
arr1

array([[5, 2, 9, 9],
       [9, 6, 5, 7],
       [7, 7, 8, 4]])

In [95]:
arr2

array([[9, 3, 3, 6],
       [4, 4, 7, 9],
       [7, 5, 6, 6]])

In [96]:
arr1-arr2

array([[-4, -1,  6,  3],
       [ 5,  2, -2, -2],
       [ 0,  2,  2, -2]])

In [98]:
np.subtract(arr1,arr2)

array([[-4, -1,  6,  3],
       [ 5,  2, -2, -2],
       [ 0,  2,  2, -2]])

---


In [100]:
np.multiply(arr1,arr2)

array([[45,  6, 27, 54],
       [36, 24, 35, 63],
       [49, 35, 48, 24]])

In [101]:
np.mod(arr1,arr2)

array([[5, 2, 0, 3],
       [1, 2, 5, 7],
       [0, 2, 2, 4]])

In [102]:
np.power(arr1,arr2)

array([[ 1953125,        8,      729,   531441],
       [    6561,     1296,    78125, 40353607],
       [  823543,    16807,   262144,     4096]])

# 11. statestical function


In [104]:
arr1

array([[5, 2, 9, 9],
       [9, 6, 5, 7],
       [7, 7, 8, 4]])

In [103]:
np.mean(arr1)

6.5

In [106]:
np.std(arr1)

2.101586702153082

In [107]:
np.median(arr1)

7.0

In [108]:
np.var(arr1)

4.416666666666667