Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.


## Ans:-

In [1]:
import numpy as np

In [2]:
list_=['1','2','3','4','5']

In [3]:
array_list=np.array(object=list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [9]:
type(list_)

list

In [10]:
array_list.dtype

dtype('<U1')

---
---

# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


## Ans:-

In [12]:
for i in list_:
    print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for i in array_list:
    print(array_list.dtype)

<U1
<U1
<U1
<U1
<U1


---
---

# Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)



## Ans:-

In [14]:
array_list = np.array(object = list_, dtype = int)

In [15]:
array_list

array([1, 2, 3, 4, 5])

In [16]:
array_list.dtype

dtype('int32')

In [19]:
type(list_)

list

In [20]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [21]:
for i in array_list:
    print(array_list.dtype)

int32
int32
int32
int32
int32


---
---

# Q4. Write a code to find the following characteristics of variable, num_array:
* (i) shape
* (ii) size


## Ans:-

In [22]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [23]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
num_array.shape

(2, 3)

In [25]:
num_array.size

6

---
---

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]


## Ans:-

In [28]:
array1=np.zeros((3,3))

In [29]:
array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

---
---

# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

## Ans:-

In [34]:
array2=np.identity(5)
array2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---
---